### PR TITLE
Add CaT app

### PR DESCRIPTION
**Pull request by mikevader**
Hopefully I've done that stuff right and compliant with naming conventions.

I assumed I do not need a dedicated repo for the helm charts and it is in a root folder of the project. (A set the replication to zero as there are no images yet ...)

### CODE REVIEW

**Comment by christiansiegel** [comment]
You also need to add it to the bootstrap/values.yaml ;-)

**Comment by christiansiegel** [comment]
Also, you should create a dedicated config repo. I think ArgoCD will try to apply all folders that don't start with a dot in their name.

**Comment by christiansiegel** [comment]
> Also, you should create a dedicated config repo. I think ArgoCD will try to apply all folders that don't start with a dot in their name.

After thinking about it, that was not entirely true: only our "sync apps" web hook will try to add all folders to the config in this repo here. So if you don't use it, it should technically work with one repo.

However, I would still recommend separating code from deployment config. Just imagine the continuous deployment use case:

1. You create a new code commit
2. This triggers a new build
3. After the build the deployment will be updated (e.g. via our gitopscli), which creates a new commit in the *same* repo
4. This triggers a new build... infinite loop

**Review by christiansiegel — CHANGES_REQUESTED** [review]
(see comments above)

**Comment by mikevader** [comment]
Ok then I split up the repos. I kinda dislike the idea of separating the same information into different repos. because they all change for the same reason.
But I follow probably your example: a separate project outside the baloise one.

**Comment by christiansiegel** [comment]
> Ok then I split up the repos. I kinda dislike the idea of separating the same information into different repos. because they all change for the same reason.
> But I follow probably your example: a separate project outside the baloise one.

Or just create a `codes-and-texts-deployment` repo in the `baloise-incubator` org. This way the deployment config is where the incubator cluster is ;-)

**Review by christiansiegel — APPROVED** [review]

**Pull request merged**
